import { TurboModuleRegistry, type TurboModule } from 'react-native';

export interface Spec extends TurboModule {
  getConstants(): {
    // Listener types
    LISTENER_ENROUTE_MANAGER: number;
    LISTENER_TASKS: number;
    LISTENER_AGENTS: number;
    LISTENER_SESSIONS: number;
    LISTENER_PICKUPS: number;

    // EnRoute Manager events
    ENROUTE_MANAGER_LOGIN_COMPLETED: number;
    ENROUTE_MANAGER_LOGGED_OUT: number;
    ENROUTE_MANAGER_STARTED: number;
    ENROUTE_MANAGER_STOPPED: number;
    ENROUTE_MANAGER_SYNCED: number;
    ENROUTE_MANAGER_SHOW_NOTIFICATION: number;
    ENROUTE_MANAGER_AUTHENTICATION_NEEDED: number;
    ENROUTE_MANAGER_ORG_CONFIG_UPDATED: number;
    ENROUTE_MANAGER_SELF_AGENT_UPDATED: number;
    ENROUTE_MANAGER_SHIFT_STARTED: number;
    ENROUTE_MANAGER_SHIFT_COMPLETED: number;
    ENROUTE_MANAGER_SHIFT_START_FAILED: number;
    ENROUTE_MANAGER_SHIFT_COMPLETE_FAILED: number;
    ENROUTE_MANAGER_LOCATION_ACCURACY_UPDATED: number;
    ENROUTE_MANAGER_ORG_PREDEFINED_MESSAGES_UPDATED: number;

    // Task Manager events
    TASKS_TASK_LIST_CHANGED: number;
    TASKS_TASK_STARTED: number;
    TASKS_TASK_START_FAILED: number;
    TASKS_OPERATION_COMPLETED: number;
    TASKS_OPERATION_COMPLETION_FAILED: number;
    TASKS_TASK_PHASE_CHANGED: number;
    TASKS_OPERATION_TICKET_CHANGED: number;
    TASKS_TASK_METADATA_UPDATE_SUCCEEDED: number;
    TASKS_TASK_METADATA_UPDATE_FAILED: number;
    TASKS_TASK_TRAVEL_MODE_CHANGED: number;
    TASKS_TASK_DURATION_CHANGED: number;
    TASKS_TASK_DESTINATION_CHANGED: number;
    TASKS_TASK_TRANSFERRED: number;
    TASKS_TASK_CHAT_MESSAGES_CHANGED: number;
    TASKS_TASK_ROUTE_CHANGED: number;
    TASKS_TASK_CREATED: number;
    TASKS_TASK_CREATE_FAILED: number;

    // Agent Manager events
    AGENTS_AGENT_LIST_CHANGED: number;
    AGENTS_AGENT_CREATED: number;
    AGENTS_AGENT_CREATION_FAILED: number;
    AGENTS_AGENT_UPDATED: number;
    AGENTS_AGENT_UPDATE_FAILED: number;

    // Session Manager events
    SESSIONS_SESSION_LIST_CHANGED: number;
    SESSIONS_SESSION_STARTED: number;
    SESSIONS_SESSION_START_FAILED: number;
    SESSIONS_SESSION_COMPLETED: number;
    SESSIONS_SESSION_COMPLETION_FAILED: number;
    SESSIONS_SESSION_ACTIVE_TASK_CHANGED: number;
    SESSIONS_SESSION_ACTIVE_TASK_PHASE_CHANGED: number;
    SESSIONS_SESSION_COMPLETION_DELAYED: number;
    SESSIONS_SESSION_ARRIVE_FAILED: number;
    SESSIONS_SESSION_DEPART_FAILED: number;
    SESSIONS_SESSION_ACTIVE_TASK_ROUTE_UPDATED: number;

    // Pickup Manager events
    PICKUPS_PICKUP_LIST_CHANGED: number;
    PICKUPS_PICKUP_ACCEPTED: number;
    PICKUPS_PICKUP_COMPLETED: number;
    PICKUPS_PICKUP_FAILED_TO_COMPLETE: number;
    PICKUPS_PICKUP_PHASE_UPDATED: number;
    PICKUPS_PICKUP_PHASE_UPDATE_FAILED: number;
    PICKUPS_PICKUP_ASSIGNED: number;
    PICKUPS_PICKUP_ASSIGN_FAILED: number;
    PICKUPS_PICKUP_TICKET_AVAILABLE: number;
    PICKUPS_PICKUP_MESSAGES_CHANGED: number;
    PICKUPS_PICKUP_CHANGED: number;
    PICKUPS_PICKUP_CHAT_MESSAGES_CHANGED: number;
  };
}

export default TurboModuleRegistry.getEnforcing<Spec>('EnRouteEvents');